export const border = {
  name: 'should render border',
  style: `<style>
#app {
  font-size: 16px;
  width: 100px;
  height: 100px;
  background-color: red;
  border-color: black;
  border: solid;
  border-width: 10px 10px 0.625em 10px;
}
</style>`,
  node: '',
  image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAAXNSR0IArs4c6QAAAgRJREFUeF7t3UEKw0AMwMD0/49uaV9g6GB8UM5GaySWkFNez/O8n54zBl4FOdPit0hBbvUoyLEeBSnINQPH9ukdUpBjBo6t0w0pyDEDx9YZ35A+5/8r9xU9eQoysQRmCgIkSkRBpE3AKgiQKBEFkTYBqyBAokQURNoErIIAiRJREGkTsAoCJEpEQaRNwCoIkCgRBZE2AasgQKJEFETaBKyCAIkSURBpE7AKAiRKREGkTcAqCJAoEQWRNgGrIECiRBRE2gSsggCJElEQaROwCgIkSkRBpE3AKgiQKBEFkTYBqyBAokQURNoErIIAiRJREGkTsAoCJEpEQaRNwCoIkCgRBZE2AasgQKJEFETaBKyCAIkSURBpE7AKAiRKREGkTcAqCJAoEQWRNgGrIECiRBRE2gSsggCJElEQaROwCgIkSkRBpE3AKgiQKBEFkTYBqyBAokQURNoErIIAiRJREGkTsAoCJEpEQaRNwCoIkCgRBZE2AasgQKJEFETaBKyCAIkSURBpE7AKAiRKREGkTcAqCJAoEQWRNgGrIECiRBRE2gSsggCJElEQaROwCgIkSkRBpE3AKgiQKBEFkTYBqyBAokQURNoELB4E7BRiYOAbrn/XD0RtjRRky/TwnIIMRW2NFWTL9PCcggxFbY0VZMv08JyCDEVtjRVky/TwnIIMRW2NfQC90bQBHTK9eQAAAABJRU5ErkJggg==',
}
